// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * e​r​r​o​r​:​ ​g​u​i​l​d​ ​n​o​t​ ​f​o​u​n​d
	 */
	ERROR_GUILD_NOT_FOUND: string
	/**
	 * e​r​r​o​r​:​ ​c​h​a​n​n​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	ERROR_CHANNEL_NOT_FOUND: string
	/**
	 * e​r​r​o​r​:​ ​u​n​k​n​o​w​n​ ​e​r​r​o​r
	 */
	ERROR_UNKNOWN: string
	/**
	 * e​r​r​o​r​:​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​ ​c​a​n​'​t​ ​b​e​ ​s​e​n​d​e​r
	 */
	SENDER_ADD_ERROR_RECEIVER_CONFLICT: string
	/**
	 * e​r​r​o​r​:​ ​c​h​a​n​n​e​l​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
	 */
	SENDER_ADD_ERROR_ALREADY_EXISTS: string
	/**
	 * a​d​d​e​d​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​ ​<​#​{​c​h​a​n​n​e​l​}​>
	 * @param {string} channel
	 */
	SENDER_ADD_SUCCESS: RequiredParams<'channel'>
	/**
	 * n​o​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​s​ ​f​o​u​n​d​ ​i​n​ ​t​h​i​s​ ​s​e​r​v​e​r
	 */
	SENDER_LIST_SUCCESS_EMPTY: string
	/**
	 * S​e​n​d​e​r​ ​C​h​a​n​n​e​l​s
	 */
	SENDER_LIST_SUCCESS_TITLE: string
	/**
	 * <​#​{​i​d​}​>​ ​・​ ​h​a​s​ ​{​c​o​u​n​t​}​ ​r​e​c​e​i​v​e​ ​c​h​a​n​n​e​l​s
	 * @param {number} count
	 * @param {string} id
	 */
	SENDER_LIST_SUCCESS_ITEM: RequiredParams<'count' | 'id'>
	/**
	 * d​e​l​e​t​e​d​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​ ​<​#​{​c​h​a​n​n​e​l​}​>
	 * @param {string} channel
	 */
	SENDER_DELETE_SUCCESS: RequiredParams<'channel'>
	/**
	 * e​r​r​o​r​:​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	RECEIVER_LISTEN_ERROR_SENDER_NOT_FOUND: string
	/**
	 * e​r​r​o​r​:​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​ ​c​a​n​'​t​ ​b​e​ ​s​e​n​d​e​r
	 */
	RECEIVER_LISTEN_ERROR_SENDER_CONFLICT: string
	/**
	 * e​r​r​o​r​:​ ​r​e​c​e​i​v​e​r​ ​b​i​n​d​i​n​g​ ​a​l​r​e​a​d​y​ ​e​x​i​s​t​s
	 */
	RECEIVER_LISTEN_ERROR_ALREADY_EXISTS: string
	/**
	 * s​e​t​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​ ​`​{​f​r​o​m​_​g​u​i​l​d​}​ ​>​ ​{​f​r​o​m​_​c​h​a​n​n​e​l​}​`​ ​→​ ​<​#​{​t​o​}​>
	 * @param {string} from_channel
	 * @param {string} from_guild
	 * @param {string} to
	 */
	RECEIVER_LISTEN_SUCCESS: RequiredParams<'from_channel' | 'from_guild' | 'to'>
	/**
	 * e​r​r​o​r​:​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	RECEIVER_UNLISTEN_ERROR_SENDER_NOT_FOUND: string
	/**
	 * e​r​r​o​r​:​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​ ​n​o​t​ ​f​o​u​n​d
	 */
	RECEIVER_UNLISTEN_ERROR_RECEIVER_NOT_FOUND: string
	/**
	 * d​e​l​e​t​e​d​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​ ​`​{​f​r​o​m​_​g​u​i​l​d​}​ ​>​ ​{​f​r​o​m​_​c​h​a​n​n​e​l​}​`​ ​f​r​o​m​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​ ​<​#​{​t​o​}​>
	 * @param {string} from_channel
	 * @param {string} from_guild
	 * @param {string} to
	 */
	RECEIVER_UNLISTEN_SUCCESS: RequiredParams<'from_channel' | 'from_guild' | 'to'>
	/**
	 * n​o​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​s​ ​f​o​u​n​d​ ​i​n​ ​t​h​i​s​ ​s​e​r​v​e​r
	 */
	RECEIVER_LIST_SUCCESS_EMPTY: string
	/**
	 * R​e​c​e​i​v​e​r​ ​C​h​a​n​n​e​l​s
	 */
	RECEIVER_LIST_SUCCESS_TITLE: string
	/**
	 * <​#​{​i​d​}​>​ ​・​ ​i​s​ ​l​i​s​t​e​n​i​n​g​ ​t​o​ ​{​c​o​u​n​t​}​ ​s​e​n​d​e​r​ ​c​h​a​n​n​e​l​s
	 * @param {number} count
	 * @param {string} id
	 */
	RECEIVER_LIST_SUCCESS_ITEM: RequiredParams<'count' | 'id'>
	/**
	 * d​e​l​e​t​e​d​ ​r​e​c​e​i​v​e​r​ ​c​h​a​n​n​e​l​ ​<​#​{​c​h​a​n​n​e​l​}​>
	 * @param {string} channel
	 */
	RECEIVER_DELETE_SUCCESS: RequiredParams<'channel'>
}

export type TranslationFunctions = {
	/**
	 * error: guild not found
	 */
	ERROR_GUILD_NOT_FOUND: () => LocalizedString
	/**
	 * error: channel not found
	 */
	ERROR_CHANNEL_NOT_FOUND: () => LocalizedString
	/**
	 * error: unknown error
	 */
	ERROR_UNKNOWN: () => LocalizedString
	/**
	 * error: receiver channel can't be sender
	 */
	SENDER_ADD_ERROR_RECEIVER_CONFLICT: () => LocalizedString
	/**
	 * error: channel already exists
	 */
	SENDER_ADD_ERROR_ALREADY_EXISTS: () => LocalizedString
	/**
	 * added sender channel <#{channel}>
	 */
	SENDER_ADD_SUCCESS: (arg: { channel: string }) => LocalizedString
	/**
	 * no sender channels found in this server
	 */
	SENDER_LIST_SUCCESS_EMPTY: () => LocalizedString
	/**
	 * Sender Channels
	 */
	SENDER_LIST_SUCCESS_TITLE: () => LocalizedString
	/**
	 * <#{id}> ・ has {count} receive channels
	 */
	SENDER_LIST_SUCCESS_ITEM: (arg: { count: number, id: string }) => LocalizedString
	/**
	 * deleted sender channel <#{channel}>
	 */
	SENDER_DELETE_SUCCESS: (arg: { channel: string }) => LocalizedString
	/**
	 * error: sender channel not found
	 */
	RECEIVER_LISTEN_ERROR_SENDER_NOT_FOUND: () => LocalizedString
	/**
	 * error: receiver channel can't be sender
	 */
	RECEIVER_LISTEN_ERROR_SENDER_CONFLICT: () => LocalizedString
	/**
	 * error: receiver binding already exists
	 */
	RECEIVER_LISTEN_ERROR_ALREADY_EXISTS: () => LocalizedString
	/**
	 * set receiver channel `{from_guild} > {from_channel}` → <#{to}>
	 */
	RECEIVER_LISTEN_SUCCESS: (arg: { from_channel: string, from_guild: string, to: string }) => LocalizedString
	/**
	 * error: sender channel not found
	 */
	RECEIVER_UNLISTEN_ERROR_SENDER_NOT_FOUND: () => LocalizedString
	/**
	 * error: receiver channel not found
	 */
	RECEIVER_UNLISTEN_ERROR_RECEIVER_NOT_FOUND: () => LocalizedString
	/**
	 * deleted sender channel `{from_guild} > {from_channel}` from receiver channel <#{to}>
	 */
	RECEIVER_UNLISTEN_SUCCESS: (arg: { from_channel: string, from_guild: string, to: string }) => LocalizedString
	/**
	 * no receiver channels found in this server
	 */
	RECEIVER_LIST_SUCCESS_EMPTY: () => LocalizedString
	/**
	 * Receiver Channels
	 */
	RECEIVER_LIST_SUCCESS_TITLE: () => LocalizedString
	/**
	 * <#{id}> ・ is listening to {count} sender channels
	 */
	RECEIVER_LIST_SUCCESS_ITEM: (arg: { count: number, id: string }) => LocalizedString
	/**
	 * deleted receiver channel <#{channel}>
	 */
	RECEIVER_DELETE_SUCCESS: (arg: { channel: string }) => LocalizedString
}

export type Formatters = {}
